### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by HeliaHashemipour** [shijianjian/DIA#1]
Hi,
What does the dataset directory should look like?

**Comment by shijianjian** [comment]
Hi, I normally use something like:
```
Mydata:
    0 - normal
    1 - abnormal
```

**Comment by HeliaHashemipour** [comment]
I mean, for example, for the Kvasir dataset your directory is like this:
train
        - normal
 test
       - anomaly
I want to know how you give your dataset into your model.

**Comment by shijianjian** [comment]
It is like this:
```
Mydata:
    train:
        0_normal
        1_abnormal
    test:
        0_normal
        1_abnormal
```
I added 0/1 to make sure the dataloader loads 0 by default.
